check for tools

diff --git a/os-auth b/os-auth
--- a/os-auth
+++ b/os-auth
@@ -16,6 +16,13 @@ if [[ $SOURCED -eq 0 ]]; then
   exit 1
 fi
 
+# check for openstack client tools
+which openstack > /dev/null
+if [ ! $? -eq 0 ]; then
+  echo -e "[ERROR]: OpenStack Python libraries not found. Exiting."
+  exit 1
+fi
+
 # check for new openstack-client version
 if [ "$(openstack --version 2>&1 | awk '{ print $2}' | awk -F'.' '{print $1}')" -lt 3 ]; then
   echo -e "[ERROR]: OpenStack client tools version too old. Please refer to README.md and install virtualenv and requirements.txt. Exiting."
