Changed to getent hosts instead of mysql resolveip script

diff --git a/os-project-create b/os-project-create
--- a/os-project-create
+++ b/os-project-create
@@ -12,6 +12,13 @@ if [ ! $? -eq 0 ]; then
   echo -e "[ERROR]: OpenStack Python libraries not found. Exiting."
   exit 1
 fi
+
+which getent > /dev/null
+if [ ! $? -eq 0 ]; then
+  echo -e "[ERROR]: Getent libraries not found. Needed for \"getent hosts\" command. Exiting."
+  exit 1
+fi
+
 #
 
 # check for new openstack-client version
@@ -22,7 +29,7 @@ fi
 
 # check for proxy ip
 # ls3cloud1.informatik.uni-wuerzburg.de must point to proxy IP 
-if [ "$(resolveip ls3cloud1.informatik.uni-wuerzburg.de -s)" != "132.187.12.42" ]; then 
+if [ "$(getent hosts ls3cloud1.informatik.uni-wuerzburg.de | awk '{ print $1 }')" != "132.187.12.42" ]; then 
 	echo "[ERROR]: ls3cloud1.informatik.uni-wuerzburg.de must point to proxy IP"
 	echo "Change dns resolution to 132.187.12.42 (proxy server), otherwise auth will fail due to SSL cert issues. Exiting." 
 	exit 1
